.Dd $Mdocdate$
.Dt DSBMixer
.Sh ABOUT
.Nm DSBMixer
is a tabbed Qt (GTK+) mixer for FreeBSD®. For each installed mixer
device,
.Nm
opens a tab. It adds a new mixer tab at runtime when you
plug in an USB sound device.
.Nm
allows you set amplification, to select recording sources, and to choose
your default audio device.
.Sh INSTALLATION
.Ss Dependencies
.Nm
depends on
.Em devel/qt5-buildtools , devel/qt5-core , devel/qt5-linguisttools ,
.Em devel/qt5-qmake , x11-toolkits/qt5-gui ,
and
.Em x11-toolkits/qt5-widgets

In order to save settings,
.Nm
requires
.Em sysutils/dsbwrtsysctl
.Ss Getting the source code
.Bd -literal
# git clone https://github.com/mrclksr/DSBMixer.git
# git clone https://github.com/mrclksr/dsbcfg.git
.Ss Building and installation
# cd DSBMixer && qmake

# make && make install
.Ed

or if you don't want devd support:
.Bd -literal
# make -DWITHOUT_DEVD && make install
.Ed
.Sh USAGE
.Bd -literal
Usage: dsbmixer [-hi]
   -i: Start dsbmixer as tray icon
.Ed

